services:
  softdes:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: softdes_img
    ports:
      - 8080:8080
    volumes:
      - softdes_volume:/app/

volumes:
  softdes_volume: